package com.example.network.dto.room

data class Room(
    val roomTitle: String,
    val teamBgCode: String,
    val thumbnailUrl: String,
    val msgWelcom: String,
    val risingYn: String,
    val roomState: Int,
    val bjProfileImage: String,
    val subjectType: String,
    val bjMemNo: String,
    val teamMedalUrl: String,
    val roomNo: Int,
    val countEntry: Int,
    val typeImage: Int,
    val codeLink: String,
    val guestProfileImage: String,
    val imageBackground: String,
    val bjNickName: String,
    val dayLiveDjRank: Int,
    val playTime: Int,
    val startDate: String,
    val countLiveMax: Int,
    val countGood: Int,
    val totRoomScore: Int,
    val bjProfileImageYn: String,
    val countLiveMem: Int,
    val bjBirthYear: String,
    val countByeol: Int,
    val bjMemSex: String,
    val teamEdgeUrl: String,
    val teamBgUrl: String,
    val typeMedia: String
)